### ISSUE TITLE
Inhalte für "Milestones" erarbeiten

### ISSUE THREAD

**Issue by cariboula** [community-garden/community-garden.github.io#6]
**Beschreibung**
Als Interessent des Pergola-Projektes möchte ich erfahren, auf welchem Stand das Projekt aktuell ist und wann mit welchen Features zu rechnen ist.

**Lösungsoption**
Die Sektion Milestones / Meilensteine ist im Blog nicht gefüllt. Die Inhalte aus dem Gantt-Chart könnten aufbereitet und etwas abgespeckt dargestellt werden. Aufbereitung als Grafik denkbar.

Ergänzend Kommentar von Marie:
Ich würde die "Project"-Seite auch noch mit der Info ergänzen, wann es eine erste Version geben wird bzw was gerade der Status ist, vielleicht auch mit Link zu bereits existierenden Repos auf Github, wenn diese öffentlich sind.

- [x] Meilensteine gemäß Projektverlauf formulieren, Gantt anpassen
- [x] Grafik (vereinfachter Screenshot) einfügen
- [x] Website betexten (Meilensteine, Logbuch)
- [x] Link zu detailierter Grafik aktualisieren
- [x] Link zur Demoversion
- [x] Website übersetzen + Link in erster Zeile zur zweiten Sprachversion
- [x] online stellen
- [x] Grafikgröße anpassen

**Comment by bastiion** [comment]
https://www.ganttproject.biz/

[projektplan.gan.zip](https://github.com/community-garden/community-garden.github.io/files/5697491/projektplan.gan.zip)

**Comment by gemeinga-manager** [comment]
![grafik](https://user-images.githubusercontent.com/72280627/102493140-0426cb00-4073-11eb-9c50-a538c43388fa.png)


So sieht deine Datei aus, wenn ich sie bei mir öffne. Mach hier mal bitte eine Markierung rein, wo die Darstellung d.E. nicht stimmt. Was meinst du mir "zu Meilensteinen zu machen"?

**Comment by gemeinga-manager** [comment]
@bastiion Warum haben wir denn jetzt zusätzlich noch zwei Bilder im Blogartikel? Da würde mir eins reichen, um zu zeigen, was ein Balkendiagramm ist. Gern können wir auch das zur hochauflösenden Variante verlinken, die seperat öffnet - falls sich jemand für den Inhalt interessiert.

**Comment by bastiion** [comment]
> @bastiion Warum haben wir denn jetzt zusätzlich noch zwei Bilder im Blogartikel? Da würde mir eins reichen, um zu zeigen, was ein Balkendiagramm ist. Gern können wir auch das zur hochauflösenden Variante verlinken, die seperat öffnet - falls sich jemand für den Inhalt interessiert.

Ja da hast du recht, ich dachte es ist vielleicht übersichtlicher wenn man es in zwei Zeiträume teilt. Du kannst ja auch wenn du möchtest die Exportfunktion von ganttproject probieren.

![sketch1608232809832.png](https://user-images.githubusercontent.com/758789/102533244-71535400-40a5-11eb-8b0d-acb22987953e.png)

**Comment by gemeinga-manager** [comment]
@bastiion Ich frage zur Sicherheit nochmal nach: 
Toplevel Gießplan - in der Zeile gibt´s eine Raute beim Start (blau)
Toplevel Was geht? - in der Zeile ist eine Spange über die Zeiträume der aufgelisteten Einzelaufgaben: grau (Standard)
Toplevel Workshops und Termine, Erntereif, E-Paper, Gartenkarte -  in der Zeile ist eine Spange über die Zeiträume der aufgelisteten Einzelaufgaben: schwarz (Standard)
Toplevel Dukumentation und Test - in der Zeile gibt´s eine Raute beim Start (grau)

Die Frage ist nun, warum sich das in Darstellung und Farbe unterscheidet, obwohl so ziemlich alles auf Standard eingestellt ist, oder?

**Comment by gemeinga-manager** [comment]
[201218_projektplan.zip](https://github.com/community-garden/community-garden.github.io/files/5714745/201218_projektplan.zip)

Ich konnte oben stehende Mänge (haben mich akut genervt, nachdem ich sie entdeckt hatte ;-)) beheben, indem ich die jeweiligen Toplevel nochmal neu angelegt  und die Einzelaufgaben drunter geschoben habe. Das Farbproblem habe ich mit manueller Einstellung ausgemerzt und festgestellt, dass es wohl gar keine Standardfarbe gibt. Da habe ich mich von einer uneindeutigen Darstellung verwirren lassen.

Außerdem habe ich die Aufgaben-Bezeichnungen noch systematisiert und mit unserer Modulliste abgeglichen.
Die Aufgabe "Kalender" gehört für mich zur Basis-Implementierung, ebenso finde ich die herausgelöste "Gartenkarte" noch strittig. Aber vielleicht ist es auch gar nicht sooo wichtig, in welcher Zeile die nun steht.

Ich füge einen neuen (entschlankten) Screenshot ein. Wollen wir die detaillierte Grafik auch noch mal aktualisieren? Wo soll die gespeichert sein? Den von dir gewählten Speicherplatz (https://raw.githubusercontent.com/wiki/....) finde ich leider nicht.

**Comment by gemeinga-manager** [comment]
![Screenshot 2020-12-18 101101](https://user-images.githubusercontent.com/72280627/102597251-a8178180-411a-11eb-958d-b10ce2b3e5f1.jpg)

**Comment by gemeinga-manager** [comment]
@bastiion Ich habe die Meilensteine ausformuliert. Übernimmst du bitte das Übersetzen? Ist es möglich, die englische Version drunter zu setzen und aus der ersten Zeile zu verlinken?

https://github.com/community-garden/community-garden.github.io/wiki/Meilensteine

**Comment by bastiion** [comment]
@gemeinga-manager 

> Wollen wir die detaillierte Grafik auch noch mal aktualisieren? 

Ja 

> Wo soll die gespeichert sein? Den von dir gewählten Speicherplatz (https://raw.githubusercontent.com/wiki/....) finde ich leider nicht.

Kann leider nur per git aktualisiert werden. Würde ich dir gern mal zeigen


Ganttproject hat übrigens eine Export Funktion.

**Comment by gemeinga-manager** [comment]
![201218_projektplan](https://user-images.githubusercontent.com/72280627/102685377-736dfd80-41e0-11eb-871d-6fcb15532428.png)

@bastiion Ich schlussfolgere aus dem Hinweis, dass du keine Änderungen an meiner Version von gestern mehr vornehmen möchtest? Anbei die exportierte Datei und die Bitte eines Terminvorschlages (Rocket.Chat). ;-)

**Comment by cariboula** [comment]
@bastiion Die Milestones sind ready to deploy, liegt alles hier: https://github.com/community-garden/community-garden.github.io/wiki/Milestones 
Bitte check vor / nach deployment nochmal, ob das mit dem Bild nun klappt (auch mobil! - so wie in den anderen Blogartikeln gut realisiert)

**Comment by pminf** [comment]
@bastiion Bitte deployen.
